//! Out-of-band absolute numbers behind the shape claims
//! (docs/design/syntax.md §16; docs/specification.md §10.2). Run per
//! milestone: `cargo bench -p themelios-syntax`. These prove wall-clock
//! magnitudes on one machine; they cannot prove complexity class — the
//! CI shape test holds that.

use criterion::Criterion;
use themelios_base::source::{Source, SourceId};
use themelios_syntax::attach::attachments;
use themelios_syntax::dialect::Dialect;
use themelios_syntax::equiv::{Certificate, equivalent};
use themelios_syntax::fusion::separator;
use themelios_syntax::parse::parse;
use themelios_syntax::tree::{SyntaxElement, SyntaxKind};

const UNIT: &str = "% leading\np(X, f(Y)) :- q(X; Y), not r(X), X = 1..3, #sum { W,T : t(T,W) } >= 4, &sum { x, -y : p } <= 3. % trailing\n";

fn admitted(units: usize) -> Source {
    Source::new(SourceId::new(0), UNIT.repeat(units)).expect("bench text admits")
}

fn parsing(c: &mut Criterion) {
    for units in [64usize, 1024, 8192] {
        let source = admitted(units);
        c.bench_function(&format!("parse/{units}-rules"), |b| {
            b.iter(|| parse(std::hint::black_box(&source), Dialect::Clingo));
        });
    }
}

fn certifying(c: &mut Criterion) {
    for units in [64usize, 1024] {
        let source = admitted(units);
        let left = parse(&source, Dialect::Clingo);
        let right = parse(&source, Dialect::Clingo);
        c.bench_function(&format!("equivalent/{units}-rules"), |b| {
            b.iter(|| {
                equivalent(
                    std::hint::black_box(&left),
                    &right,
                    Certificate::UpToSpelling,
                )
            });
        });
    }
}

fn attaching(c: &mut Criterion) {
    for units in [64usize, 1024] {
        let root = parse(&admitted(units), Dialect::Clingo).syntax();
        c.bench_function(&format!("attachments/{units}-rules"), |b| {
            b.iter(|| attachments(std::hint::black_box(&root)).count());
        });
    }
}

fn oracle(c: &mut Criterion) {
    let root = parse(&admitted(64), Dialect::Clingo).syntax();
    let tokens: Vec<_> = root
        .descendants_with_tokens()
        .filter_map(SyntaxElement::into_token)
        .filter(|t| t.kind() != SyntaxKind::WHITESPACE)
        .collect();
    c.bench_function("separator/every-pair-of-64-rules", |b| {
        b.iter(|| {
            for pair in tokens.windows(2) {
                std::hint::black_box(separator(&pair[0], &pair[1], Dialect::Clingo));
            }
        });
    });
}

// The harness, written out rather than generated by `criterion_group!`
// and `criterion_main!`: the macros expand to exactly this, and the
// generated group is a public function without documentation, which
// the workspace's denied `missing_docs` refuses. Same behavior, one
// documented item.

/// The scaling group: every bench above, under criterion's default
/// configuration as adjusted by the command line.
pub fn scaling() {
    let mut criterion: Criterion = Criterion::default().configure_from_args();
    parsing(&mut criterion);
    certifying(&mut criterion);
    attaching(&mut criterion);
    oracle(&mut criterion);
}

fn main() {
    scaling();
    Criterion::default().configure_from_args().final_summary();
}
