//! Out-of-band absolute numbers behind the shape claims
//! (docs/design/base.md §10; docs/specification.md §10.2). Run per
//! milestone: `cargo bench -p themelios-base`. These prove wall-clock
//! magnitudes on one machine; they cannot prove complexity class —
//! the CI shape test holds that.

use criterion::Criterion;
use themelios_base::diagnostic::{Diagnostic, DiagnosticId, Label, Severity};
use themelios_base::line::{ColumnEncoding, LineIndex};
use themelios_base::source::{Source, SourceId, SourceSet};
use themelios_base::span::{ByteOffset, Location, Span};
use themelios_base::view::human;

/// One repeated line with multi-byte content, so every size exercises
/// the wide-character tables.
const LINE: &str = "p(a). % é🦀 comment\n";

fn text_of(bytes: usize) -> String {
    LINE.repeat(bytes / LINE.len() + 1)
}

fn admitted(bytes: usize) -> Source {
    Source::new(SourceId::new(0), text_of(bytes)).expect("bench text admits")
}

fn line_index_of(c: &mut Criterion) {
    for kib in [256usize, 1024, 4096] {
        let source = admitted(kib * 1024);
        c.bench_function(&format!("LineIndex::of/{kib}KiB"), |b| {
            b.iter(|| LineIndex::of(std::hint::black_box(&source)));
        });
    }
}

fn position_queries(c: &mut Criterion) {
    for kib in [64usize, 4096] {
        let source = admitted(kib * 1024);
        let index = LineIndex::of(&source);
        let len = source.end().get() as usize;
        // Boundary offsets: multiples of the repeated line's length.
        let offsets: Vec<ByteOffset> = (0..4096usize)
            .map(|i| (i * (len / 4096)) / LINE.len() * LINE.len())
            .map(|raw| ByteOffset::new(raw as u32))
            .collect();
        c.bench_function(&format!("position/4096-queries/{kib}KiB"), |b| {
            b.iter(|| {
                for &offset in &offsets {
                    let _ =
                        std::hint::black_box(index.position(offset, ColumnEncoding::Utf16Units));
                }
            });
        });
    }
}

fn human_rendering(c: &mut Criterion) {
    let mut catalog = SourceSet::new();
    let file = catalog
        .add("bench.lp".to_owned(), text_of(512 * LINE.len()))
        .expect("bench text admits");
    for labels in [16u32, 256] {
        let mut diagnostic = Diagnostic::new(
            DiagnosticId::new("syntax", "unexpected-token"),
            Severity::Error,
            "bench".to_owned(),
            label_on_line(file, 0),
        )
        .expect("non-empty headline");
        for line in 1..labels {
            diagnostic = diagnostic.with_secondary(label_on_line(file, line));
        }
        c.bench_function(&format!("human/{labels}-labels"), |b| {
            b.iter(|| human(std::hint::black_box(&diagnostic), &catalog));
        });
    }
}

fn label_on_line(source: SourceId, line: u32) -> Label {
    let start = line * LINE.len() as u32;
    Label {
        location: Location {
            source,
            span: Span::new(ByteOffset::new(start), ByteOffset::new(start + 4))
                .expect("ordered endpoints"),
        },
        message: Some("here".to_owned()),
    }
}

// The harness, written out rather than generated by `criterion_group!`
// and `criterion_main!`: the macros expand to exactly this, and the
// generated group is a public function without documentation, which
// the workspace's denied `missing_docs` refuses. Same behavior, one
// documented item.

/// The scaling group: every bench above, under criterion's default
/// configuration as adjusted by the command line.
pub fn scaling() {
    let mut criterion: Criterion = Criterion::default().configure_from_args();
    line_index_of(&mut criterion);
    position_queries(&mut criterion);
    human_rendering(&mut criterion);
}

fn main() {
    scaling();
    Criterion::default().configure_from_args().final_summary();
}
