//! Scaling shapes for the analysis (docs/design/analysis.md §10), measured out of
//! band as criterion benchmarks: the strongly-connected-components decomposition
//! (§4) linear in the graph, and — as those surfaces land — `Analysis::of` linear in
//! `program + edges`. Each shape lands with the surface it measures; the test suite
//! asserts the shapes hold (the in-suite scaling tripwires, `tests/scc_laws.rs`),
//! while these benchmarks measure the absolute numbers across doubling sizes, so a
//! super-linear regression shows as a curve (docs/specification.md §10.2). Run with
//! `cargo bench`.

use criterion::{BenchmarkId, Criterion};

use themelios_analysis::depend::DependencyGraph;
use themelios_program::program::{Atom, Program, Rule, Statement};
use themelios_program::provenance::WithProvenance;
use themelios_program::symbol::Name;

fn name(text: &str) -> Name {
    Name::new(text).expect("a valid identifier")
}

fn rule(head: usize, body: usize) -> WithProvenance<Statement> {
    WithProvenance::constructed(Statement::Rule(Rule::new(
        Atom::constant(name(&format!("p{head}"))),
        Atom::constant(name(&format!("p{body}"))),
    )))
}

/// A chain `p0 :- p1. … p_{n-1} :- p_n.` — a deep acyclic dependency graph.
fn chain(n: usize) -> Program {
    Program::of((0..n).map(|i| rule(i, i + 1)))
}

/// A cycle `p0 :- p1. … p_{n-1} :- p0.` — one strongly-connected component of `n`.
fn cycle(n: usize) -> Program {
    Program::of((0..n).map(|i| rule(i, (i + 1) % n)))
}

/// The decomposition (`DependencyGraph::of`, the walk and the iterative Tarjan) over
/// a chain and a cycle at doubling sizes — linear in the graph (§4).
fn decompose(c: &mut Criterion) {
    let mut group = c.benchmark_group("scc_decompose");
    for n in [1_000_usize, 4_000, 16_000] {
        let chain = chain(n);
        group.bench_with_input(BenchmarkId::new("chain", n), &chain, |b, program| {
            b.iter(|| DependencyGraph::of(program));
        });
        let cycle = cycle(n);
        group.bench_with_input(BenchmarkId::new("cycle", n), &cycle, |b, program| {
            b.iter(|| DependencyGraph::of(program));
        });
    }
    group.finish();
}

// The harness, written out rather than generated by `criterion_group!` and
// `criterion_main!`: the macros expand to exactly this, and the generated group is a
// public function without documentation, which the workspace's denied `missing_docs`
// refuses. Same behavior, one documented item.

/// The scaling group: every bench above, under criterion's default configuration as
/// adjusted by the command line.
pub fn scaling() {
    let mut criterion: Criterion = Criterion::default().configure_from_args();
    decompose(&mut criterion);
}

fn main() {
    scaling();
    Criterion::default().configure_from_args().final_summary();
}
