//! Scaling shapes (docs/design/program.md §16), measured out of band as criterion benchmarks:
//! each body lands with the surface it measures. The unifier's shapes are here — a deep ground
//! symbol against its non-ground twin (the near-linear decision §11.1/§15 promises, the case a
//! monolithic ground representation would make quadratic) and two non-ground terms — so the cost
//! *shape* is measured, not only asserted by the depth witnesses in the suite. Run with `cargo bench`.

use criterion::{BenchmarkId, Criterion};

use themelios_program::program::Atom;
use themelios_program::symbol::{Name, VarName};
use themelios_program::term::{Term, Variable};
use themelios_program::unify::mgu;

fn name(text: &str) -> Name {
    Name::new(text).expect("a valid identifier")
}

fn variable(text: &str) -> Term {
    Term::Variable(Variable::Named(
        VarName::new(text).expect("a valid variable name"),
    ))
}

/// `f(f(… bottom …))` — `depth` `f`-applications over the bottom term.
fn nest(bottom: Term, depth: usize) -> Term {
    let mut term = bottom;
    for _ in 0..depth {
        term = Term::Function {
            name: name("f"),
            arguments: vec![term],
        };
    }
    term
}

const DEPTHS: [usize; 5] = [1_000, 2_000, 4_000, 8_000, 16_000];

fn mgu_scaling(c: &mut Criterion) {
    // A deep ground symbol against its non-ground twin — the case that was Θ(depth²) before the
    // ground side was decomposed into the unification graph (§11.1). Timings should grow linearly.
    let mut ground_vs_nested = c.benchmark_group("mgu/ground_vs_nested");
    for depth in DEPTHS {
        let ground = Atom::new(
            name("p"),
            [nest(
                Term::Function {
                    name: name("a"),
                    arguments: Vec::new(),
                },
                depth,
            )],
        );
        let nested = Atom::new(name("p"), [nest(variable("X"), depth)]);
        ground_vs_nested.bench_with_input(BenchmarkId::from_parameter(depth), &depth, |b, _| {
            b.iter(|| mgu(&ground, &nested));
        });
    }
    ground_vs_nested.finish();

    // Two non-ground terms of the same shape, a variable at each bottom — the term-vs-term path.
    let mut term_vs_term = c.benchmark_group("mgu/term_vs_term");
    for depth in DEPTHS {
        let left = Atom::new(name("p"), [nest(variable("X"), depth)]);
        let right = Atom::new(name("p"), [nest(variable("Y"), depth)]);
        term_vs_term.bench_with_input(BenchmarkId::from_parameter(depth), &depth, |b, _| {
            b.iter(|| mgu(&left, &right));
        });
    }
    term_vs_term.finish();
}

// The harness, written out rather than generated by `criterion_group!` and `criterion_main!`:
// the macros expand to exactly this, and the generated group is a public function without
// documentation, which the workspace's denied `missing_docs` refuses. Same behavior, one
// documented item.

/// The scaling group: every bench above, under criterion's default configuration as adjusted by
/// the command line.
pub fn scaling() {
    let mut criterion: Criterion = Criterion::default().configure_from_args();
    mgu_scaling(&mut criterion);
}

fn main() {
    scaling();
    Criterion::default().configure_from_args().final_summary();
}
